### ISSUE TITLE
app.js role play

### ISSUE THREAD

**Issue by le-wei** [jaruba/node-vlc-multiscreen#2]
I run this demo. The following error occurred 
===========================
Uncaught TypeError: Cannot read property 'addRule' of undefined
    at Object.<anonymous> (F:\test\node_modules\wcjs-player\index.js:41:36)
    at Module._compile (module.js:648:30)
    at Object.Module._extensions..js (module.js:665:10)
    at Module.load (module.js:569:32)
    at tryModuleLoad (module.js:532:12)
    at Function.Module._load (module.js:524:3)
    at Module.require (module.js:592:17)
    at require (internal/module.js:11:18)
    at self.require (<anonymous>:11:26)
==============================
I do not know why.can you help me 。Thank you

**Comment by jaruba** [comment]
https://github.com/jaruba/wcjs-player/issues/34
